# .cargo/config.toml
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-args=-Wl,--subsystem,windows"]

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin21.4-clang"
#ar = "x86_64-apple-darwin21.4-ar"

[target.x86_64-unknown-linux-gnu]
# Specify custom linker (if needed)
# linker = "/usr/bin/gcc"
# Specify custom rustflags (if needed)
# rustflags = ["-C", "link-args=-some-arg"]


##  ----- uncomment if using cross: ---- ##
# [package.metadata.cross.target.x86_64-pc-windows-gnu]
# rustflags = ["-C", "link-args=-Wl,--subsystem,windows"]

# [package.metadata.cross.target.x86_64-apple-darwin]
# image = "ghcr.io/cross-rs/x86_64-apple-darwin-cross:local"